# Generated by Django 4.2.6 on 2023-10-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_document', models.FileField(upload_to='documents/')),
                ('summarized_text', models.TextField()),
                ('questions', models.JSONField()),
            ],
        ),
    ]
