# Generated by Django 4.2.6 on 2023-10-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarizeddocument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
