# Generated by Django 4.2.6 on 2023-10-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_materials', '0003_summarizeddocument_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarizeddocument',
            name='image',
        ),
        migrations.AddField(
            model_name='summarizeddocument',
            name='application_design',
            field=models.TextField(default=''),
        ),
    ]
